add patches
Signed-off-by: Tin Lai <oscar@tinyiu.com>

diff --git a/makepkg b/makepkg
--- a/makepkg
+++ b/makepkg
@@ -40,7 +40,7 @@ unset CDPATH
 # Ensure GREP_OPTIONS doesn't screw with our grep calls
 unset GREP_OPTIONS
 
-set -x
+# set -x
 
 resolve_link() {
   if type greadlink >/dev/null 2>&1; then
@@ -261,6 +261,7 @@ missing_source_file() {
 }
 
 run_pacman() {
+  return
 	local cmd cmdescape
 	if [[ $1 = -@(T|Q)*([[:alpha:]]) ]]; then
 		cmd=("$PACMAN_PATH" "$@")
@@ -757,24 +758,24 @@ create_package() {
 	# ensure all elements of the package have the same mtime
 	find . -exec touch -h -d @$SOURCE_DATE_EPOCH {} +
 
-	msg2 "$(gettext "Generating .MTREE file...")"
-	list_package_files | LANG=C bsdtar -cnf - --format=mtree \
-		--options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
-		--null --files-from - --exclude .MTREE | gzip -c -f -n > .MTREE
-	touch -d @$SOURCE_DATE_EPOCH .MTREE
+	# msg2 "$(gettext "Generating .MTREE file...")"
+	# list_package_files | LANG=C bsdtar -cnf - --format=mtree \
+	# 	--options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
+	# 	--null --files-from - --exclude .MTREE | gzip -c -f -n > .MTREE
+	# touch -d @$SOURCE_DATE_EPOCH .MTREE
 
-	msg2 "$(gettext "Compressing package...")"
-	# TODO: Maybe this can be set globally for robustness
-	shopt -s -o pipefail
-	list_package_files | LANG=C bsdtar --no-fflags --no-read-sparse -cnf - --null --files-from - |
-		compress_as "$PKGEXT" > "${pkg_file}" || ret=$?
-
-	shopt -u -o pipefail
-
-	if (( ret )); then
-		error "$(gettext "Failed to create package file.")"
-		exit $E_PACKAGE_FAILED
-	fi
+	# msg2 "$(gettext "Compressing package...")"
+	# # TODO: Maybe this can be set globally for robustness
+	# shopt -s -o pipefail
+	# list_package_files | LANG=C bsdtar --no-fflags --no-read-sparse -cnf - --null --files-from - |
+	# 	compress_as "$PKGEXT" > "${pkg_file}" || ret=$?
+  #
+	# shopt -u -o pipefail
+  #
+	# if (( ret )); then
+	# 	error "$(gettext "Failed to create package file.")"
+	# 	exit $E_PACKAGE_FAILED
+	# fi
 }
 
 create_debug_package() {
@@ -859,19 +860,19 @@ create_srcpackage() {
 	msg2 "$(gettext "Compressing source package...")"
 	cd_safe "${srclinks}"
 
-	# TODO: Maybe this can be set globally for robustness
-	shopt -s -o pipefail
-	LANG=C bsdtar --no-fflags --no-read-sparse -cLf - ${pkgbase} | compress_as "$SRCEXT" > "${pkg_file}" || ret=$?
-
-	shopt -u -o pipefail
-
-	if (( ret )); then
-		error "$(gettext "Failed to create source package file.")"
-		exit $E_PACKAGE_FAILED
-	fi
-
-	cd_safe "${startdir}"
-	rm -rf "${srclinks}"
+	# # TODO: Maybe this can be set globally for robustness
+	# shopt -s -o pipefail
+	# LANG=C bsdtar --no-fflags --no-read-sparse -cLf - ${pkgbase} | compress_as "$SRCEXT" > "${pkg_file}" || ret=$?
+  #
+	# shopt -u -o pipefail
+  #
+	# if (( ret )); then
+	# 	error "$(gettext "Failed to create source package file.")"
+	# 	exit $E_PACKAGE_FAILED
+	# fi
+  #
+	# cd_safe "${startdir}"
+	# rm -rf "${srclinks}"
 }
 
 install_package() {
@@ -1176,7 +1177,7 @@ PACKAGER=${PACKAGER:-"Unknown Packager"}
 # set pacman command if not already defined
 PACMAN=${PACMAN:-pacman}
 # save full path to command as PATH may change when sourcing /etc/profile
-PACMAN_PATH=$(type -P $PACMAN)
+# PACMAN_PATH=$(type -P $PACMAN)
 
 # check if messages are to be printed using color
 if [[ -t 2 && $USE_COLOR != "n" ]] && check_buildenv "color" "y"; then
